
# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'MiniEcho' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MiniEcho
pod 'AFNetworking', '~> 3.1.0'
 
 pod 'SDWebImage', '~> 3.8.2'
 
 pod 'Masonry', '~> 1.0.2'
 
 pod 'MJRefresh', '~> 3.1.12'
 
 pod 'MJExtension', '~> 3.0.13'
 
 pod 'SVProgressHUD', '~> 2.0.3'
 
 pod 'AFNetworking', '~> 3.1.0'
 
 pod 'YYText', '~> 1.0.7'
 
 pod 'Reachability', '~> 3.2'

  target 'MiniEchoTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'MiniEchoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
